services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: agentic-test
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - app_network

networks:
  app_network:
    name: app_network
    driver: bridge